import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

<html lang="en" className="relative">
<link rel="icon" href="/favicon.png" type="image/x-icon" />
<body className={twMerge(dmSans.className, "antialiased bg-[#EAEEFE]")}>{children}</body>
</html>
    </ClerkProvider>
  );
}



 